### ISSUE TITLE
Since Windows support was added pipe not closing properly

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#34] opened 2021-10-05 01:26 UTC
I believe this was added in https://github.com/vijaymarupudi/nvim-fzf/commit/5934f3bcaff204940567d1becb0c9563fac075ca, the pipe feeding lines into fzf isn't closing properly resulting in a a never ending loading indicator with `sk`. For some reason this does not appear to affect `fzf`, but even prior to this bug `fzf` was stopping the loading indicator regardless if I called `cb(nil, fn)` inside the callback to signal EOF.

This is how it looks like, look at the `<` right of the prompt

![nvim-fzf-bug](https://user-images.githubusercontent.com/59988195/135946074-4d27ffc8-b95b-4ab3-a215-745334b5d6a1.gif)

**Comment by vijaymarupudi** [comment] 2021-10-05 01:35
Should be fixed now? This was a regression, deleted a line of code I shouldn't have.

**Comment by ibhagwan** [comment] 2021-10-05 01:40
Yap, works now, I was just going to suggest that line was the problem :-)

**Closed** 2021-10-05 01:53 UTC

**Comment by vijaymarupudi** [comment] 2021-10-05 13:45
Great!

**Comment by vijaymarupudi** [comment] 2021-10-09 17:24
Windows support is not complete, I need a tester to make it work, since I don't have a computer. Please create a new issue if you're willing to help!

**Comment by cpkio** [comment] 2021-10-09 17:47
> I need a tester to make it work

I'm all yours
